### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by teneresa** [Aura-healthcare/Aura_mobile_app#7]
Hi, my name is Valeria. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your app. If it's something you're interested in, please, let me know!
Best,
Valeria

**Comment by clecoued** [comment]
Hi Valeria, 
Thanks for your message ! We are always pleased to welcome new contributors. There is definitely work to do on the icon design. 
It would nice if we can have a quick chat on [appear.in ](www.appear.in) so I could give you more information about the AURA project. 
When would be the best time for you ?

Regards, 
Clement

**Comment by clecoued** [comment]
Hi Valeria, 
What about tomorrow at 3pm (Paris time GMT +2) ? 
We can have a discussion on this channel -> [https://appear.in/aura-asso](https://appear.in/aura-asso)
Is that ok for you ?
Clement

**Comment by teneresa** [comment]
Yes, that's fine :)

**Comment by clecoued** [comment]
Great !

**Comment by teneresa** [comment]
Ahh.. it's a video chat? My equipment and internet are not so good for this, sorry.. Can we chat somewhere via text messages?

**Comment by teneresa** [comment]
Perfect, thanks!

**Comment by teneresa** [comment]
How can I connect to the chat? I use this link https://appear.in/aura-asso, but seems it doesn't work for me..

**Comment by clecoued** [comment]
Ok well, otherwise you can join us on [Slack](https://associationaura.slack.com/messages)

**Comment by clecoued** [comment]
I did not see you on chat - you can send me an email at contact@aura.healthcare and I will answer you and give you more details about the project

**Comment by teneresa** [comment]
Ok. Thanks!

**Comment by teneresa** [comment]
Hi Clément, unfortunately, I'm not able to reach you by this e-mail address as well. All my messages were returned with this error: 

"This is the mail system at host mo80.mail-out.ovh.net.
I'm sorry to have to inform you that your message could not be delivered to one or more recipients. It's attached below...
The mail system <florianbreton@outlook.fr>: host eur.olc.protection.outlook.com[104.47.8.33] said: 550 5.7.1 Unfortunately, messages from [178.32.228.80] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3140). "

Do you have another address or can you send me any test message to teneresa@gmail.com?

**Comment by clecoued** [comment]
Hi Valeria, 
I confirm that I received your email. I will answer today.
